# Generated by Django 4.2.13 on 2024-06-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='direction',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
