# Generated by Django 2.1.15 on 2024-06-06 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_trade_direction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
