# Generated by Django 2.1.15 on 2024-06-06 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_trade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trade',
            new_name='Trades',
        ),
    ]
